#DATA SOURCE
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/financedb?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update